name: "WCAG Accessibility Scanner"
author: "mohammedfarhank"
description: "Automatically scan HTML files for WCAG accessibility compliance using axe-core and Puppeteer"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "eye"
  color: "blue"
inputs:
  email: 
    description: The committer's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}
  scan_mode:
    description: "Scan mode: auto (default), all (entire repo), or affected (changed files only)"
    required: false
    default: "auto"
  output_dir:
    description: "Output directory for reports"
    required: false
    default: "./reports"
